from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=ROOT/'app/src/main/java/com/yagay/nfcdoorcard/xposed/NfcInjectionModule.java'
s=p.read_text()

old='''            boolean persistedApplyFromOldProcess = cfg.active && cfg.generation > 0L &&\n                    cfg.handledGeneration == cfg.generation && "SUCCESS".equals(cfg.commandStatus) &&\n                    cfg.commandPid > 0 && cfg.commandPid != pid;\n            if (persistedApplyFromOldProcess && !isLifecycleVerified(cfg.generation, pid, cfg.uid)) {\n                synchronized (this) {\n                    lifecycleReapplyPending = true;\n                    lifecycleRecoveryGeneration = cfg.generation;\n                    if (lifecycleRecoveryStartedAt == 0L) lifecycleRecoveryStartedAt = System.currentTimeMillis();\n                }\n            }\n'''
new='''            // Any terminal desired APPLY whose RF proof is no longer fresh is a lifecycle\n            // reapply, even when com.android.nfc kept the same PID. This is crucial for adapter\n            // OFF -> ON: the controller resets but the Java service process may survive. The\n            // controller epoch makes stale proof detectable, and this natural OEM RF write is the\n            // preferred place to reapply instead of manufacturing a share-mode refresh.\n            boolean terminalDesiredApply = cfg.active && cfg.generation > 0L &&\n                    cfg.handledGeneration == cfg.generation && "SUCCESS".equals(cfg.commandStatus);\n            if (terminalDesiredApply && !isLifecycleVerified(cfg.generation, pid, cfg.uid)) {\n                synchronized (this) {\n                    lifecycleReapplyPending = true;\n                    lifecycleRecoveryGeneration = cfg.generation;\n                    if (lifecycleRecoveryStartedAt == 0L) lifecycleRecoveryStartedAt = System.currentTimeMillis();\n                }\n            }\n'''
if old not in s: raise SystemExit('old persisted lifecycle block not found')
s=s.replace(old,new)

old2='''        v.put("controller_epoch", nextEpoch);\n        persistRefreshRuntime("LIFECYCLE_INVALIDATED", "", reason, cfg.generation, false);\n        writeValuesWithRetry(v, 8, 75L);\n'''
new2='''        v.put("controller_epoch", nextEpoch);\n        // Epoch invalidation is a correctness barrier, not diagnostic telemetry. Commit it\n        // synchronously so an immediately following ADAPTER_STATE_ON or OEM RF write cannot read\n        // the previous epoch. Normal status/log writes remain asynchronous.\n        if (!writeValuesSynchronously(v, 5, 25L)) {\n            Log.w(TAG, "CONTROLLER EPOCH synchronous write failed reason=" + reason +\n                    " generation=" + cfg.generation + " nextEpoch=" + nextEpoch);\n        }\n        persistRefreshRuntime("LIFECYCLE_INVALIDATED", "", reason, cfg.generation, false);\n'''
if old2 not in s: raise SystemExit('async epoch write block not found')
s=s.replace(old2,new2)

anchor='''    private void writeValuesWithRetry(ContentValues values, int attempts, long delayMs) {\n        final ContentValues copy = new ContentValues(values);\n        stateSyncExecutor.execute(() -> {\n            for (int i = 0; i < attempts; i++) {\n                Context ctx = currentContext();\n                if (ctx != null) {\n                    try { ctx.getContentResolver().insert(CONFIG_URI, copy); return; }\n                    catch (Throwable e) { Log.w(TAG, "status write attempt " + (i + 1) + " failed: " + e.getMessage()); }\n                }\n                sleep(delayMs);\n            }\n        });\n    }\n'''
insert=anchor+'''\n    private boolean writeValuesSynchronously(ContentValues values, int attempts, long delayMs) {\n        ContentValues copy = new ContentValues(values);\n        for (int i = 0; i < attempts; i++) {\n            Context ctx = currentContext();\n            if (ctx != null) {\n                try {\n                    ctx.getContentResolver().insert(CONFIG_URI, copy);\n                    return true;\n                } catch (Throwable e) {\n                    Log.w(TAG, "sync state write attempt " + (i + 1) + " failed: " + e.getMessage());\n                }\n            }\n            if (i + 1 < attempts) sleep(delayMs);\n        }\n        return false;\n    }\n'''
if anchor not in s: raise SystemExit('writeValuesWithRetry anchor not found')
s=s.replace(anchor,insert)
p.write_text(s)
